version: "3"
services:
  network-tools:
    image: alpine:latest
    command: tail -f /dev/null
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ors
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres-db
    ports:
      - 8070:8080

  assignment-service:
    build:
      context: ./assignment-logic-service
    ports:
      - "8084:8084"
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    # Uncomment the following lines if you need live code updates without rebuilding the container
    # volumes:
    #   - ./src:/deployments/src
    depends_on:
      - kafka
      - postgres-db

  order-service:
    build:
      context: ./order-management-service
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    # Uncomment the following lines if you need live code updates without rebuilding the container
    # volumes:
    #   - ./src:/deployments/src
    depends_on:
      - kafka
      - postgres-db

  printer-service:
    build:
      context: ./printer-management-service
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    # Uncomment the following lines if you need live code updates without rebuilding the container
    # volumes:
    #   - ./src:/deployments/src
    depends_on:
      - kafka
      - postgres-db

volumes:
  postgres-data:
